version: '3'

services:
  node-app:
    build: .
    image: node-app
    environment:
      - MONGODB_URL=mongodb://mongodb:27019/instadam
    ports:
      - '5123:5123'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/instadam
      - /usr/instadam/node_modules
    networks:
      - node-network

  mongodb:
    image: mongo:4.2.1-bionic
    command: mongod --port 27019
    ports:
      - '27019:27019'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
